import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900 text-white`}>
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            // Default toast styles
            style: {
              background: "#333",
              color: "#fff",
            },
            // Success toast styles
            success: {
              style: {
                background: "#4ADE80",
              },
            },
            // Error toast styles
            error: {
              style: {
                background: "#EF4444",
              },
            },
            // Loading toast styles
            loading: {
              style: {
                background: "#333",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
